{
 "title": "Pizza dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_creation_latency_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "endpoint_latency_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Pizza Revenue Per Minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Revenue/min"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza Purchases"
    },
    {
     "expr": "rate(pizzas_failed_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza Failures"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "active_users_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "activeUsersCount"
    }
   ]
  },
  {
   "title": "Auth counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(auth_attempts_success_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_attempts_failed_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percent_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "http_requests_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "http_requests_get_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "GET"
    },
    {
     "expr": "http_requests_post_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "http_requests_put_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "PUT"
    },
    {
     "expr": "http_requests_delete_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}